### ISSUE TITLE
Error after Intellij update to 2017.3.2

### ISSUE THREAD

**Issue by GreenDude** [getgauge/Intellij-Plugin#312] opened 2018-01-22 08:40 UTC
### Expected behavior
Spec file finds the step implementation
### Actual behavior
"C:\Program Files\Gauge\bin\gauge.exe" run --machine-readable --hide-suggestion --simple-console C:/Users/gmosin/Desktop/JGauge/at-fasttrack-realex/specs/JGaugeFrameworkExample.spec
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:380)
	at org.reflections.Reflections.<init>(Reflections.java:126)
	at com.thoughtworks.gauge.scan.ClasspathScanner.createReflections(ClasspathScanner.java:59)
	at com.thoughtworks.gauge.scan.ClasspathScanner.scan(ClasspathScanner.java:37)
	at com.thoughtworks.gauge.GaugeRuntime.connectSynchronously(GaugeRuntime.java:82)
	at com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:54)
[ValidationError] C:\Users\gmosin\Desktop\JGauge\at-fasttrack-realex\specs\JGaugeFrameworkExample.spec:10 Connection closed [127.0.0.1:51445] cause: read tcp 127.0.0.1:51440->127.0.0.1:51445: wsarecv: An existing connection was forcibly closed by the remote host. => 'Given the "ServerName" server is online'
[ValidationError] C:\Users\gmosin\Desktop\JGauge\at-fasttrack-realex\specs\JGaugeFrameworkExample.spec:11 write tcp 127.0.0.1:51440->127.0.0.1:51445: use of closed network connection => 'When a functional test simulating the activity of "6" users is performed "2" times with a rampUp of "1" in a "serial" run'
[ValidationError] C:\Users\gmosin\Desktop\JGauge\at-fasttrack-realex\specs\JGaugeFrameworkExample.spec:12 write tcp 127.0.0.1:51440->127.0.0.1:51445: use of closed network connection => 'Then the response is sent, matching expectations'process C:\ProgramData\Oracle\Java\javapath\java.exe with pid 14052 quit unexpectedly. exit status 1Successfully generated html-report to => C:\Users\gmosin\Desktop\JGauge\at-fasttrack-realex\reports\html-report\index.html
Specifications:	0 executed	0 passed	0 failed	0 skipped
Scenarios:	0 executed	0 passed	0 failed	0 skipped
![error spec](https://user-images.githubusercontent.com/35530169/35211748-6c0ee3da-ff60-11e7-80b1-a3daa86197f1.png)

### Steps to reproduce
1.Update Intellij
2.Open previously working project
3.Run spec file

### Version information

* IntelliJ version and edition(Community/Ultimate): Community 2017.3.3
* OS information: Windows 10 Enterprise
* Gauge IntelliJ plugin version :0.3.9.nightly-2017-12-04
* Project uses Maven built into Intellij
```
Gauge version: 0.9.7
Commit Hash: bc9784c

Plugins
-------
html-report (4.0.3)
java (0.6.6)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.0)

```

**Comment by riju91** [comment] 2018-01-22 09:56
Can you please attach the project for which you are witnessing this behavior?

**Comment by GreenDude** [comment] 2018-01-23 11:31
[jmeter_gauge_framework.zip](https://github.com/getgauge/Intellij-Plugin/files/1655649/jmeter_gauge_framework.zip)
For some reason the defect disappeared the next morning.
P.S. Sadly I am not able to reproduce the problem again.
P.P.S. The project uses a company proprietory library that I have no right to upload.

**Comment by riju91** [comment] 2018-01-23 12:25
@GreenDude I am closing this issue since we are not able to reproduce it. Please feel free to reopen it again in case it appears again. Thanks

**Closed by riju91** 2018-01-23 12:25 UTC
