### ISSUE TITLE
Even though the signature with parameters are present it shows as unimplemented in IDE

### ISSUE THREAD

**Issue by sguptatw** [getgauge/Intellij-Plugin#147] opened 2016-05-04 05:59 UTC
### Expected behavior
If the signature with parameters match the step description it should not show me an error

### Actual behavior
Even though the signature with parameters are present it shows as unimplemented in IDE

### Steps to reproduce
1. Create a spec
```
sfsdf
======

sfsdf
-----
* something
    |HEADER|
    |value|
    |value|

* a new step

* something

    |HEADER|
    |value|
    |value|
```
2. Create an implementation
```
    @Step("something <table>")
    public void implementation1(Object table) {

    }
```
3. It still shows as unimplemented.
4. However the execution works as expected.

### Versions

* 0.1.1
* Gauge version: 0.4.1.nightly-2016-05-03

Plugins
-------
html-report (2.1.1.nightly-2016-05-02)
java (0.4.0.nightly-2016-05-02)
xml-report (0.1.2)

**Comment by kashishm** [comment] 2016-06-16 06:15
Unable to reproduce this issue.

**Version info:**

```
Gauge version: 0.5.1
gauge-java: 0.4.1
IntelliJ version: IntelliJ IDEA 2016.1.3
Gauge plugin version: 0.2.0
```

**Comment by apoorvam** [comment] 2016-07-27 09:10
This issue is fixed in
Gauge version: 0.6.1
Gauge-Java: 0.4.2
Gauge IntelliJ plugin version: 0.2.2.nighty-2016-07-13

**Closed** 2016-08-01 08:49 UTC
Labels: grammar, in QA
