### ISSUE TITLE
Find out unimplemented steps

### ISSUE THREAD

**Issue by kupna** [getgauge/Intellij-Plugin#74] opened 2015-06-10 08:05 UTC
When some steps are unimplemented you cannot find out on make of the gauge project because there is no summary that shows all the unimplemented steps. This should also be visible in the project explorer.

**Comment by prateekbaheti** [comment] 2015-06-10 08:52
Duplicate of #62. 
Closing this one.

**Closed by prateekbaheti** 2015-06-10 08:52 UTC
