### ISSUE TITLE
com.google.protobuf.InvalidProtocolBufferException: Message missing required fields: stepValidateRequest.numberOfParameters

### ISSUE THREAD

**Issue by akalaiselvan** [getgauge/Intellij-Plugin#368] opened 2019-01-21 11:29 UTC
1. It was running perfect in my environment 
2. I just did some changes in my project folder structure 
3.After that facing this problem ... i am just blind please help me ..
### Version information

* IntelliJ version and edition(Community/Ultimate): 
* OS information:
* Gauge IntelliJ plugin version:
* Does the project uses any Build tool(Gradle/Maven)?
```
Run gauge -v on your system and paste the results here
```

**Comment by sriv** [comment] 2019-01-22 02:14
duplicate of getgauge/gauge-java#227

**Closed by sriv** 2019-01-22 02:14 UTC
Labels: community
