### ISSUE TITLE
Unimplemented steps are not highlighted

### ISSUE THREAD

**Issue by sguptatw** [getgauge/Intellij-Plugin#166] opened 2016-06-15 04:18 UTC
**Expected behavior**
Unimplemented steps should be highlighted.

**Actual behavior**
In a new file. Type the entire content but still the unimplemented steps are not getting highlighted.

**Steps to replicate**
1. Create a spec file

```
# Should show unimplemented steps
```
1. Once some text is pasted on the spec, type steps after that it shows them as unimplemented.

```
* does not show unimplemented steps
```
1. It does not highlight the unimplemented step. Moreover even after closing the file and re-opening it there is no highlighting of the step.

**Version**

```
Gauge version: 0.5.1.nightly-2016-06-14

Plugins
-------
html-report (2.1.1.nightly-2016-06-02)
java (0.4.1.nightly-2016-06-14)
```

**Comment by kashishm** [comment] 2016-06-17 06:46
Fixing #155 should fix this.

**Comment by kashishm** [comment] 2017-01-04 06:10
@sguptatw I cannot reproduce this with the latest nightly. Please close this issues if it is fixed.

**Closed** 2017-01-11 08:45 UTC
Labels: bug, ready for QA
