### ISSUE TITLE
Gauge  plugin not compatible with IntelliJ Ultimate 2020.1

### ISSUE THREAD

**Issue by AliAMQ** [getgauge/Intellij-Plugin#431] opened 2020-04-10 13:07 UTC
### Expected behavior
The Gauge syntax should be recognized by IntelliJ.

### Actual behavior
Gauge script is not recognized by IntelliJ and no feature to run the test.

### Steps to reproduce
1.Install the latest gauge plugin: 0.2.4 at the time of reporting the issue
2.Open a spec file in IntelliJ
3.Gauge syntax is not known to IntelliJ

### Version information

* Ultimate IntelliJ 2020.1 
* OS information: Ubuntu 18.04.3 LTS
* Gauge IntelliJ plugin version: 0.2.4
* Maven is used as build tool
```
auge version: 1.0.7
Commit Hash: 477b4ae

Plugins
-------
html-report (4.0.8)
java (0.7.2)
screenshot (0.0.1)
```

**Comment by sriv** [comment] 2020-04-13 10:00
duplicate of #430

**Closed by sriv** 2020-04-13 10:00 UTC
