### ISSUE TITLE
gauge 0.2.4 plugin does not work on intellij 2020.2

### ISSUE THREAD

**Issue by ccrj1105** [getgauge/Intellij-Plugin#445] opened 2020-07-29 16:12 UTC
### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Version information

* IntelliJ version and edition(Community/Ultimate): 
* OS information:
* Gauge IntelliJ plugin version:
* Does the project uses any Build tool(Gradle/Maven)?
```
Run gauge -v on your system and paste the results here
```

**Comment by zabil** [comment] 2020-07-29 17:34
Duplicate of #445

**Closed as completed by zabil** 2020-07-29 17:34 UTC

**Comment by jreznot** [comment] 2020-07-31 12:47
We have just released 0.4.0 compatible with IntelliJ IDEA 2020.
