### ISSUE TITLE
Data table given inline not getting generated as a parameter in a concept

### ISSUE THREAD

**Issue by sguptatw** [getgauge/Intellij-Plugin#145] opened 2016-04-28 11:23 UTC
### Expected behavior
Data table given inline should generate as a parameter in a concept

### Actual behavior
Data table given inline not getting generated as a parameter in a concept

### Steps to reproduce
1. Create a concept 
```
# Concept Heading
table:codeStatus.csv

* step2
    |HEADER|
    |value|
    |value|

* step and table with space

    |HEADER|
    |value|
    |value|
```
2. Create a step implementation for `step2` and `step and table with space`.
3. It does not generate the table parameter.

### Gauge version
```
Gauge version: 0.4.1.nightly-2016-04-19

Plugins
-------
html-report (2.1.1.nightly-2016-04-27)
java (0.3.4.nightly-2016-04-19)
xml-report (0.1.2)
```

**Comment by BugDiver** [comment] 2016-06-13 10:50
Duplicate of #143.

**Closed by BugDiver** 2016-06-13 10:50 UTC
Labels: type: bug
