### ISSUE TITLE
Got exception on reload of project

### ISSUE THREAD

**Issue by BugDiver** [getgauge/Intellij-Plugin#156] opened 2016-06-06 08:38 UTC
```
Already disposed: Project (Disposed) test
java.lang.AssertionError: Already disposed: Project (Disposed) test
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:170)
	at com.intellij.openapi.roots.ProjectRootManager.getInstance(ProjectRootManager.java:42)
	at com.intellij.psi.impl.search.JavaSourceFilterScope.<init>(JavaSourceFilterScope.java:42)
	at com.intellij.psi.impl.java.stubs.index.JavaAnnotationIndex.get(JavaAnnotationIndex.java:48)
	at com.intellij.psi.impl.search.AnnotatedElementsSearcher$4.compute(AnnotatedElementsSearcher.java:98)
	at com.intellij.psi.impl.search.AnnotatedElementsSearcher$4.compute(AnnotatedElementsSearcher.java:94)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:962)
	at com.intellij.psi.impl.search.AnnotatedElementsSearcher.a(AnnotatedElementsSearcher.java:94)
	at com.intellij.psi.impl.search.AnnotatedElementsSearcher.execute(AnnotatedElementsSearcher.java:62)
	at com.intellij.psi.impl.search.AnnotatedElementsSearcher.execute(AnnotatedElementsSearcher.java:38)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:45)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:75)
	at com.intellij.util.AbstractQuery.findAll(AbstractQuery.java:37)
	at com.intellij.util.InstanceofQuery.findAll(InstanceofQuery.java:38)
	at com.thoughtworks.gauge.util.StepUtil.getStepMethods(StepUtil.java:204)
	at com.thoughtworks.gauge.util.StepUtil.findStepReference(StepUtil.java:58)
	at com.thoughtworks.gauge.util.StepUtil.findStepImpl(StepUtil.java:52)
	at com.thoughtworks.gauge.reference.StepReference.resolve(StepReference.java:42)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:403)
	at com.intellij.codeInsight.TargetElementUtil.b(TargetElementUtil.java:380)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:247)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:216)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by mahendrakariya** [comment] 2016-06-09 06:26
I am not able to reproduce this issue.
Can you try clearing the cache and restarting IntelliJ?

**Comment by BugDiver** [comment] 2016-06-13 09:05
Tried again but not able to reproduce.

**Comment by kashishm** [comment] 2016-06-16 05:44
I ll close it for now, please reopen this issue if you face it again

**Closed by kashishm** 2016-06-16 05:44 UTC
Labels: bug, response needed
