### ISSUE TITLE
CNFE FindUsagesProvider

### ISSUE THREAD

**Issue by zolotov** [getgauge/Intellij-Plugin#60] opened 2015-04-15 13:00 UTC
IDEA 138.2458

```
java.lang.ClassNotFoundException: com.thoughtworks.gauge.usage.FindUsagesProvider PluginClassLoader[com.thoughtworks.gauge, 0.0.1]

java.lang.RuntimeException: java.lang.ClassNotFoundException: com.thoughtworks.gauge.usage.FindUsagesProvider PluginClassLoader[com.thoughtworks.gauge, 0.0.1]
	at com.intellij.lang.LanguageExtensionPoint$1.compute(LanguageExtensionPoint.java:45)
	at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:36)
	at com.intellij.lang.LanguageExtensionPoint.getInstance(LanguageExtensionPoint.java:53)
	at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:155)
	at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:128)
	at com.intellij.openapi.util.KeyedExtensionCollector.forKey(KeyedExtensionCollector.java:116)
	at com.intellij.lang.LanguageExtension.forLanguage(LanguageExtension.java:55)
	at com.intellij.psi.impl.cache.impl.id.IdTableBuilding.getFileTypeIndexer(IdTableBuilding.java:102)
	at com.intellij.psi.impl.cache.impl.id.IdIndex$4.map(IdIndex.java:83)
	at com.intellij.psi.impl.cache.impl.id.IdIndex$4.map(IdIndex.java:79)
	at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:398)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1758)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1690)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1638)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:101)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:97)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:279)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:905)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:298)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$3.run(ProgressManagerImpl.java:164)
	at com.intellij.openapi.progress.ProgressManager.registerIndicatorAndRun(ProgressManager.java:254)
	at com.intellij.openapi.progress.ProgressManager.registerIndicatorAndRun(ProgressManager.java:251)
	at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:224)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:197)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:151)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:293)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:405)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
Caused by: java.lang.ClassNotFoundException: com.thoughtworks.gauge.usage.FindUsagesProvider PluginClassLoader[com.thoughtworks.gauge, 0.0.1]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClass(AbstractExtensionPointBean.java:42)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:63)
	at com.intellij.openapi.extensions.CustomLoadingExtensionPointBean.instantiateExtension(CustomLoadingExtensionPointBean.java:47)
	at com.intellij.lang.LanguageExtensionPoint.access$000(LanguageExtensionPoint.java:28)
	at com.intellij.lang.LanguageExtensionPoint$1.compute(LanguageExtensionPoint.java:42)
	... 33 more
```

**Comment by kashishm** [comment] 2015-04-15 13:42
What version of the IntelliJ idea plugin are you using? 
Could you update to the latest(0.0.7)

**Comment by zolotov** [comment] 2015-04-15 13:47
@kashishm according to the stacktrace it's 0.0.1. I don't use the plugin sorry, the exception report has been delivered to JetBrains and I thought that you should know about it :)

**Comment by prateekbaheti** [comment] 2015-04-28 08:36
This has been fixed in the newer gauge plugin versions. Closing this for now. You can reopen it if the issue is seen again.

**Closed by prateekbaheti** 2015-04-28 08:36 UTC
